<?php return array (
  'keys' => 
  array (
    0 => 'index.demo',
    1 => 'biography.title',
    2 => 'biography.description',
    3 => 'site.terms',
    4 => 'site.cookies',
    5 => 'site.impressum',
    6 => 'team.description',
    7 => 'team.subtitle',
    8 => 'team.team-description',
    9 => 'salons.title',
    10 => 'salons.description',
    11 => 'index.banner-title',
    12 => 'index.banner-subtitle',
    13 => 'index.small-girl1-title',
    14 => 'index.small-girl2-title',
    15 => 'index.small-girl3-title',
    16 => 'index.small-girl3-description',
    17 => 'index.small-girl2-description',
    18 => 'index.small-girl1-description',
    19 => 'index.about-title',
    20 => 'index.about-description',
    21 => 'services.description',
    22 => 'editorial.description',
    23 => 'events.description',
    24 => 'celebrity.description',
  ),
);